module.exports = {

    getErrorDescriptionById: function(errorCode) {
        errorCode = Number(errorCode);

        const entry = errorCodes.values.find(item => item.errorCode === errorCode);
        if (entry) {
            return entry.description;
        }

        // Unknown code - lets return the ID at least
        return errorCode.toString();
    }
}

/* Currently this is repeated in 'mower_errorcode_capability' as changnig that from enum to string gives an error. And recreating the capability breaks flows */
let errorCodes = {
    "values": [
        {"errorCode": 0, "description": "---"},
        {"errorCode": 1, "description": "Outside working area"},
        {"errorCode": 2, "description": "No loop signal"},
        {"errorCode": 3, "description": "Wrong loop signal"},
        {"errorCode": 4, "description": "Loop sensor problem, front"},
        {"errorCode": 5, "description": "Loop sensor problem, rear"},
        {"errorCode": 6, "description": "Loop sensor problem, left"},
        {"errorCode": 7, "description": "Loop sensor problem, right"},
        {"errorCode": 8, "description": "Wrong PIN code"},
        {"errorCode": 9, "description": "Trapped"},
        {"errorCode": 10, "description": "Upside down"},
        {"errorCode": 11, "description": "Low battery"},
        {"errorCode": 12, "description": "Empty battery"},
        {"errorCode": 13, "description": "No drive"},
        {"errorCode": 14, "description": "Mower lifted"},
        {"errorCode": 15, "description": "Lifted"},
        {"errorCode": 16, "description": "Stuck in charging station"},
        {"errorCode": 17, "description": "Charging station blocked"},
        {"errorCode": 18, "description": "Collision sensor problem, rear"},
        {"errorCode": 19, "description": "Collision sensor problem, front"},
        {"errorCode": 20, "description": "Wheel motor blocked, right"},
        {"errorCode": 21, "description": "Wheel motor blocked, left"},
        {"errorCode": 22, "description": "Wheel drive problem, right"},
        {"errorCode": 23, "description": "Wheel drive problem, left"},
        {"errorCode": 24, "description": "Cutting system blocked"},
        {"errorCode": 25, "description": "Cutting system blocked"},
        {"errorCode": 26, "description": "Invalid sub-device combination"},
        {"errorCode": 27, "description": "Settings restored"},
        {"errorCode": 28, "description": "Memory circuit problem"},
        {"errorCode": 29, "description": "Slope too steep"},
        {"errorCode": 30, "description": "Charging system problem"},
        {"errorCode": 31, "description": "STOP button problem"},
        {"errorCode": 32, "description": "Tilt sensor problem"},
        {"errorCode": 33, "description": "Mower tilted"},
        {"errorCode": 34, "description": "Cutting stopped - slope too steep"},
        {"errorCode": 35, "description": "Wheel motor overloaded, right"},
        {"errorCode": 36, "description": "Wheel motor overloaded, left"},
        {"errorCode": 37, "description": "Charging current too high"},
        {"errorCode": 38, "description": "Electronic problem"},
        {"errorCode": 39, "description": "Cutting motor problem"},
        {"errorCode": 40, "description": "Limited cutting height range"},
        {"errorCode": 41, "description": "Unexpected cutting height adj"},
        {"errorCode": 42, "description": "Limited cutting height range"},
        {"errorCode": 43, "description": "Cutting height problem, drive"},
        {"errorCode": 44, "description": "Cutting height problem, curr"},
        {"errorCode": 45, "description": "Cutting height problem, dir"},
        {"errorCode": 46, "description": "Cutting height blocked"},
        {"errorCode": 47, "description": "Cutting height problem"},
        {"errorCode": 48, "description": "No response from charger"},
        {"errorCode": 49, "description": "Ultrasonic problem"},
        {"errorCode": 50, "description": "Guide 1 not found"},
        {"errorCode": 51, "description": "Guide 2 not found"},
        {"errorCode": 52, "description": "Guide 3 not found"},
        {"errorCode": 53, "description": "GPS navigation problem"},
        {"errorCode": 54, "description": "Weak GPS signal"},
        {"errorCode": 55, "description": "Difficult finding home"},
        {"errorCode": 56, "description": "Guide calibration accomplished"},
        {"errorCode": 57, "description": "Guide calibration failed"},
        {"errorCode": 58, "description": "Temporary battery problem"},
        {"errorCode": 59, "description": "Temporary battery problem"},
        {"errorCode": 60, "description": "Temporary battery problem"},
        {"errorCode": 61, "description": "Temporary battery problem"},
        {"errorCode": 62, "description": "Temporary battery problem"},
        {"errorCode": 63, "description": "Temporary battery problem"},
        {"errorCode": 64, "description": "Temporary battery problem"},
        {"errorCode": 65, "description": "Temporary battery problem"},
        {"errorCode": 66, "description": "Battery problem"},
        {"errorCode": 67, "description": "Battery problem"},
        {"errorCode": 68, "description": "Temporary battery problem"},
        {"errorCode": 69, "description": "Alarm! Mower switched off"},
        {"errorCode": 70, "description": "Alarm! Mower stopped"},
        {"errorCode": 71, "description": "Alarm! Mower lifted"},
        {"errorCode": 72, "description": "Alarm! Mower tilted"},
        {"errorCode": 73, "description": "Alarm! Mower in motion"},
        {"errorCode": 74, "description": "Alarm! Outside geofence"},
        {"errorCode": 75, "description": "Connection changed"},
        {"errorCode": 76, "description": "Connection NOT changed"},
        {"errorCode": 77, "description": "Com board not available"},
        {"errorCode": 78, "description": "Slipped - Mower has Slipped.Situation not solved with moving pattern"},
        {"errorCode": 79, "description": "Invalid battery combination - Invalid combination of different battery types."},
        {"errorCode": 80, "description": "Cutting system imbalance    Warning"},
        {"errorCode": 81, "description": "Safety function faulty"},
        {"errorCode": 82, "description": "Wheel motor blocked, rear right"},
        {"errorCode": 83, "description": "Wheel motor blocked, rear left"},
        {"errorCode": 84, "description": "Wheel drive problem, rear right"},
        {"errorCode": 85, "description": "Wheel drive problem, rear left"},
        {"errorCode": 86, "description": "Wheel motor overloaded, rear right"},
        {"errorCode": 87, "description": "Wheel motor overloaded, rear left"},
        {"errorCode": 88, "description": "Angular sensor problem"},
        {"errorCode": 89, "description": "Invalid system configuration"},
        {"errorCode": 90, "description": "No power in charging station"},
        {"errorCode": 91, "description": "Switch cord problem"},
        {"errorCode": 92, "description": "Work area not valid"},
        {"errorCode": 93, "description": "No accurate position from satellites"},
        {"errorCode": 94, "description": "Reference station communication problem"},
        {"errorCode": 95, "description": "Folding sensor activated"},
        {"errorCode": 96, "description": "Right brush motor overloaded"},
        {"errorCode": 97, "description": "Left brush motor overloaded"},
        {"errorCode": 98, "description": "Ultrasonic Sensor 1 defect"},
        {"errorCode": 99, "description": "Ultrasonic Sensor 2 defect"},
        {"errorCode": 100, "description": "Ultrasonic Sensor 3 defect"},
        {"errorCode": 101, "description": "Ultrasonic Sensor 4 defect"},
        {"errorCode": 102, "description": "Cutting drive motor 1 defect"},
        {"errorCode": 103, "description": "Cutting drive motor 2 defect"},
        {"errorCode": 104, "description": "Cutting drive motor 3 defect"},
        {"errorCode": 105, "description": "Lift Sensor defect"},
        {"errorCode": 106, "description": "Collision sensor defect"},
        {"errorCode": 107, "description": "Docking sensor defect"},
        {"errorCode": 108, "description": "Folding cutting deck sensor defect"},
        {"errorCode": 109, "description": "Loop sensor defect"},
        {"errorCode": 110, "description": "Collision sensor error"},
        {"errorCode": 111, "description": "No confirmed position"},
        {"errorCode": 112, "description": "Cutting system major imbalance"},
        {"errorCode": 113, "description": "Complex working area"},
        {"errorCode": 114, "description": "Too high discharge current"},
        {"errorCode": 115, "description": "Too high internal current"},
        {"errorCode": 116, "description": "High charging power loss"},
        {"errorCode": 117, "description": "High internal power loss"},
        {"errorCode": 118, "description": "Charging system problem"},
        {"errorCode": 119, "description": "Zone generator problem"},
        {"errorCode": 120, "description": "Internal voltage error"},
        {"errorCode": 121, "description": "High internal temerature"},
        {"errorCode": 122, "description": "CAN error"},
        {"errorCode": 123, "description": "Destination not reachable"},
        {"errorCode": 124, "description": "Destination blocked"},
        {"errorCode": 125, "description": "Battery needs replacement"},
        {"errorCode": 126, "description": "Battery near end of life"},
        {"errorCode": 127, "description": "Battery problem"},
        {"errorCode": 128, "description": "Multiple reference stations detected"},
        {"errorCode": 129, "description": "Auxiliary cutting means blocked"},
        {"errorCode": 130, "description": "Imbalanced auxiliary cutting disc detected"},
        {"errorCode": 131, "description": "Lifted in link arm"},
        {"errorCode": 132, "description": "EPOS accessory missing"},
        {"errorCode": 133, "description": "Bluetooth com with CS failed"},
        {"errorCode": 134, "description": "Invalid SW configuration"},
        {"errorCode": 135, "description": "Radar problem"},
        {"errorCode": 136, "description": "Work area tampered"},
        {"errorCode": 137, "description": "High temperature in cutting motor, right"},
        {"errorCode": 138, "description": "High temperature in cutting motor, center"},
        {"errorCode": 139, "description": "High temperature in cutting motor, left"},
        {"errorCode": 141, "description": "Wheel brush motor problem"},
        {"errorCode": 143, "description": "Accessory power problem"},
        {"errorCode": 144, "description": "Boundary wire problem"},
        {"errorCode": 701, "description": "Connectivity problem"},
        {"errorCode": 702, "description": "Connectivity settings restored"},
        {"errorCode": 703, "description": "Connectivity problem"},
        {"errorCode": 704, "description": "Connectivity problem"},
        {"errorCode": 705, "description": "Connectivity problem"},
        {"errorCode": 706, "description": "Poor signal quality"},
        {"errorCode": 707, "description": "SIM card requires PIN"},
        {"errorCode": 708, "description": "SIM card locked"},
        {"errorCode": 709, "description": "SIM card not found"},
        {"errorCode": 710, "description": "SIM card locked"},
        {"errorCode": 711, "description": "SIM card locked"},
        {"errorCode": 712, "description": "SIM card locked"},
        {"errorCode": 713, "description": "Geofence problem"},
        {"errorCode": 714, "description": "Geofence problem"},
        {"errorCode": 715, "description": "Connectivity problem"},
        {"errorCode": 716, "description": "Connectivity problem"},
        {"errorCode": 717, "description": "SMS could not be sent"},
        {"errorCode": 724, "description": "Communication circuit board SW must be updated"}
    ]
};